// frontend/src/components/common/UIComponents.jsx
import { useState, useCallback, createContext, useContext } from "react";


// ────── DESIGN TOKENS ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
export const T = {
  // Midnight Slate Palette
  bg:          "#0B0E14", // Deep dark background
  surface:     "#12161F", // Main panels
  surfaceAlt:  "#1A202C", // Secondary surfaces/inputs
  border:      "#2D3748", // Subtle borders
  borderLight: "#4A5568", // Visible separators
  
  // Brand & Accents
  primary:     "#6366F1", // Indigo
  primaryDim:  "rgba(99,102,241,0.12)",
  primaryGlow: "rgba(99,102,241,0.25)",
  accent:      "#F43F5E", // Rose/Soft Red
  accentDim:   "rgba(244,63,94,0.12)",
  
  // States
  gold:        "#F59E0B", // Amber/Gold
  goldDim:     "rgba(245,158,11,0.10)",
  green:       "#10B981", // Emerald
  greenDim:    "rgba(16,185,129,0.10)",
  red:         "#EF4444", 
  redDim:      "rgba(239,68,68,0.10)",
  blue:        "#3B82F6",
  
  // Text
  text:        "#F8FAFC", // High contrast text
  textMuted:   "#94A3B8", // Secondary text
  textDim:     "#475569", // Disabled/Meta text
  
  // Typography
  fontHead:    "'Plus Jakarta Sans', system-ui, sans-serif",
  fontBody:    "'Inter', system-ui, sans-serif",
  fontDevan:   "'Noto Sans Devanagari', system-ui, sans-serif",
  fontMono:    "'JetBrains Mono', monospace",
};

// ────── GLOBAL STYLES ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
export const GlobalStyles = () => (
  <style>{`
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Inter:wght@400;500;600&family=Noto+Sans+Devanagari:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap');
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    body{background:${T.bg};color:${T.text};font-family:${T.fontBody};-webkit-font-smoothing:antialiased;overflow-x:hidden}
    ::-webkit-scrollbar{width:4px;height:4px}
    ::-webkit-scrollbar-track{background:transparent}
    ::-webkit-scrollbar-thumb{background:${T.border};border-radius:2px}
    @keyframes fadeUp{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}
    @keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}
    @keyframes pulse{0%,100%{opacity:1}50%{opacity:.45}}
    @keyframes shimmer{0%{background-position:-600px 0}100%{background-position:600px 0}}
    @keyframes slideIn{from{opacity:0;transform:translateX(-8px)}to{opacity:1;transform:translateX(0)}}
    .fade-up{animation:fadeUp .45s ease both}
    .slide-in{animation:slideIn .3s ease both}
    .shimmer{background:linear-gradient(90deg,${T.surface} 25%,${T.surfaceAlt} 50%,${T.surface} 75%);background-size:600px 100%;animation:shimmer 1.5s infinite}
    input,select,textarea{font-family:${T.fontBody}}
    button{font-family:${T.fontBody}}
  `}</style>
);

// ────── MINI ICONS ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
export const I = {
  dash:     <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>,
  create:   <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>,
  posts:    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/></svg>,
  analytics:<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>,
  billing:  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/></svg>,
  settings: <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>,
  telegram: <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M11.944 0A12 12 0 1 0 12 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/></svg>,
  ig:       <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 0 0 0-12.324zM12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm6.406-11.845a1.44 1.44 0 1 0 0 2.881 1.44 1.44 0 0 0 0-2.881z"/></svg>,
  logout:   <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg>,
  check:    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><polyline points="20 6 9 17 4 12"/></svg>,
  alert:    <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>,
  link:     <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>,
  refresh:  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/></svg>,
  copy:     <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>,
  star:     <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>,
  upload:   <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="16 16 12 12 8 16"/><line x1="12" y1="12" x2="12" y2="21"/><path d="M20.39 18.39A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.3"/></svg>,
  trend:    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>,
  zap:      <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>,
  heart:    <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>,
  eye:      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>,
  chat:     <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>,
  clock:    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>,
  globe:    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>,
  aggregator:<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="2" y="2" width="20" height="20" rx="2" ry="2"/><line x1="12" y1="18" x2="12" y2="12"/><line x1="12" y1="8" x2="12" y2="8"/><path d="M7 12h10"/></svg>,
};

// ────── UTILITY COMPONENTS ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
export const Spinner = ({ size = 16, color = T.primary }) => (
  <div style={{ width: size, height: size, border: `2px solid ${color}33`, borderTopColor: color, borderRadius: "50%", animation: "spin .75s linear infinite", flexShrink: 0 }} />
);

export const Badge = ({ status }) => {
  const map = {
    posted:     { c: T.green, l: "Posted" },
    scheduled:  { c: T.gold,  l: "Scheduled" },
    ready:      { c: T.primary, l: "Ready" },
    processing: { c: T.blue,  l: "Processing" },
    failed:     { c: T.red,   l: "Failed" },
    free:       { c: T.textMuted, l: "Free" },
    starter:    { c: T.green, l: "Starter" },
    growth:     { c: T.primary, l: "Growth" },
    agency:     { c: T.accent, l: "Agency" },
    active:     { c: T.green, l: "Active" },
    cancelled:  { c: T.red,   l: "Cancelled" },
    trialing:   { c: T.gold,  l: "Trial" },
  }[status] || { c: T.textMuted, l: status || "••" };
  return <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: ".06em", textTransform: "uppercase", color: map.c, background: `${map.c}18`, padding: "3px 9px", borderRadius: 20 }}>{map.l}</span>;
};

export const StatCard = ({ label, value, sub, icon, color = T.primary, delay = 0, loading }) => (
  <div className="fade-up" style={{ animationDelay: `${delay}ms`, background: T.surface, border: `1px solid ${T.border}`, borderRadius: 16, padding: "20px 22px", position: "relative", overflow: "hidden" }}>
    <div style={{ position: "absolute", top: 0, right: 0, width: 70, height: 70, background: `radial-gradient(circle at 100% 0%, ${color}20, transparent 70%)`, borderRadius: "0 16px 0 100%" }} />
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 10 }}>
      <span style={{ fontSize: 11, color: T.textMuted, fontWeight: 600, textTransform: "uppercase", letterSpacing: ".07em" }}>{label}</span>
      <span style={{ color, opacity: .75 }}>{icon}</span>
    </div>
    {loading
      ? <div className="shimmer" style={{ height: 28, borderRadius: 6, width: "60%" }} />
      : <div style={{ fontSize: 26, fontWeight: 800, fontFamily: T.fontHead, color: T.text, lineHeight: 1 }}>{value ?? "••"}</div>
    }
    {sub && <div style={{ fontSize: 11, color: T.textMuted, marginTop: 6 }}>{sub}</div>}
  </div>
);

export const Toggle = ({ value, onChange }) => (
  <div onClick={() => onChange(!value)} style={{ width: 42, height: 22, background: value ? T.primary : T.border, borderRadius: 11, cursor: "pointer", position: "relative", transition: "background .2s", flexShrink: 0 }}>
    <div style={{ width: 16, height: 16, background: "white", borderRadius: "50%", position: "absolute", top: 3, left: value ? 23 : 3, transition: "left .2s", boxShadow: "0 1px 4px rgba(0,0,0,.3)" }} />
  </div>
);

export function useToast() {
  const [toasts, setToasts] = useState([]);
  
  const show = useCallback((msg, type = "success") => {
    const id = Date.now() + Math.random();
    setToasts(prev => [...prev.slice(-2), { id, msg, type }]);
    setTimeout(() => {
      setToasts(prev => prev.filter(t => t.id !== id));
    }, 3200);
  }, []);

  const Toast = (
    <div style={{ position: "fixed", bottom: 28, right: 28, zIndex: 1000, display: "flex", flexDirection: "column", gap: 8 }}>
      {toasts.map(toast => (
        <div key={toast.id} className="fade-up" style={{ 
          background: toast.type === "success" ? T.green : T.red, 
          color: "white", 
          padding: "12px 20px", 
          borderRadius: 12, 
          boxShadow: "0 4px 16px rgba(0,0,0,.2)", 
          display: "flex", 
          alignItems: "center", 
          gap: 10 
        }}>
          {toast.type === "success" ? I.check : I.alert}
          <span>{toast.msg}</span>
          <div onClick={() => setToasts(p => p.filter(t => t.id !== toast.id))} style={{ marginLeft: 10, cursor: "pointer", opacity: 0.7 }}>✕</div>
        </div>
      ))}
    </div>
  );
  
  return { Toast, show };
}

// ── CONTEXTS ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
export const AppContext = createContext();
export const useAppContext = () => useContext(AppContext);

// Exported from LanguageContext for global use
export { useLanguage as useLang } from "./LanguageContext";

export function makeLangValue(lang, setLang) {
  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS["en"][key] || key;
  return { lang, t, setLang };
}

// ── TRANSLATIONS ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard", create: "Create Post", posts: "My Posts",
    analytics: "Analytics", billing: "Billing", telegram: "Telegram Bot",
    aggregator: "Aggregator", admin: "Admin Panel", settings: "Settings", logout: "Sign Out",
    menu: "Menu", monthly_usage: "Monthly Usage",
    "aggregator.title": "Market Intelligence",
    "aggregator.subtitle": "Aggregator",
    "aggregator.add_account": "Add Account",
    "aggregator.tracked_accounts": "Tracked Accounts",
    "aggregator.generate_insights": "Generate AI Insights",
    "aggregator.ai_strategy": "Claude Strategy",
    "aggregator.post_ideas": "Post Ideas",
    "aggregator.market_trends": "Market Trends",
    "aggregator.feed_title": "Competitive Feed",
    "aggregator.type_owned": "Owned",
    "aggregator.type_competitor": "Competitor",
    "aggregator.type_owned_full": "Owned Account",
    "aggregator.type_competitor_full": "Competitor Account",
    "aggregator.account_type": "Account Type",
    "aggregator.synced": "Synced",
    "aggregator.syncing": "Pending",
    "aggregator.no_accounts": "No accounts yet. Add one to get started.",
    "aggregator.fetching_data": "Fetching competitor data...",
    "aggregator.sync_pending_banner": "Syncing posts in background • takes ~30 seconds",
    "aggregator.account_added_msg": "Account added! Data will sync shortly.",
    "aggregator.insights_generated_msg": "AI Insights generated!",
    "aggregator.add_modal_title": "Add Instagram Account",
    "aggregator.add_modal_desc": "Enter the username of a competitor or your own account to track.",
    "aggregator.ig_username": "Instagram Username",
    "aggregator.track_btn": "Start Tracking",
    "aggregator.refresh": "Refresh",
    "aggregator.refresh_triggered": "Sync triggered!",
    "aggregator.save_to_my_posts": "Save to My Posts",
    "aggregator.save_success": "Saved to your posts library!",
    "aggregator.feed_tab": "Feed",
    "aggregator.analytics_tab": "Analytics",
    "aggregator.accounts_tab": "Profiles",
    "aggregator.sort_recent": "Recent",
    "aggregator.sort_top": "Top Rated",
    "aggregator.enable_alerts": "Enagement Alerts",
    "aggregator.alert_threshold": "Alert if ER >",
    "aggregator.alerts_updated_msg": "Alert settings saved!",
    "aggregator.avg_weekly_posts": "Avg. Weekly Posts",
    "aggregator.competitor_avg": "Competitor Avg: {val}",
    "aggregator.top_format": "Most Viral Format",
    "aggregator.highest_er": "Highest Engagement",
    "aggregator.network_er": "Your Average ER",
    "aggregator.owned_account": "Primary Account",
    "aggregator.posting_frequency": "Posting Frequency",
    "aggregator.trending_hashtags": "Trending Hashtags",
    "aggregator.engagement_by_format": "Engagement by Format",
    "aggregator.competitor_comparison": "Competitor Benchmark",
    "aggregator.account": "Account",
    "aggregator.followers": "Followers",
    "aggregator.avg_er": "Avg ER",
    "aggregator.weekly_posts": "Posts/Wk",
    "aggregator.you": "You",
    "aggregator.owned": "Owned",
    "aggregator.content_sentiment": "Content Vibe",
    "aggregator.top_format_ai": "Winning Format",
    "aggregator.weak_spots": "Weak Spots",
    "aggregator.ai_footer": "Insights derived from latest 30 posts per account.",
    "aggregator.confirm_delete": "Stop tracking this account?",
    "aggregator.remove_account": "Remove Account",
    "admin_aggregator": "Tracked Profiles",
    "common.cancel": "Cancel",
    "common.save": "Save Changes",
    "common.upload": "Upload",
    "common.generate": "Generate",
    "common.post_now": "Post Now",
    "common.schedule": "Schedule",
    "common.processing": "Processing...",
    "common.ready": "Ready",
    "common.posted": "Posted",
    "common.failed": "Failed",
    "common.scheduled": "Scheduled",
    "common.no_posts": "No posts found",
    "common.first_photo": "Upload your first photo",
    "common.error": "Something went wrong",
    "common.success": "Operation successful",
    "billing.plan": "Your Plan",
    "billing.upgrade": "Upgrade Now",
    "settings.language": "Language",
    "settings.profile": "Profile Settings",
    "settings.instagram": "Instagram Connection",
    "dashboard.greeting_morning": "Good morning",
    "dashboard.greeting_afternoon": "Good afternoon",
    "dashboard.greeting_evening": "Good evening",
    "dashboard.analytics_overview": "Analytics Overview",
    "dashboard.monthly_posts": "Monthly Posts",
    "dashboard.reach": "Reach",
    "dashboard.engagement": "Engagement",
    "dashboard.account_status": "Account Status",
    "dashboard.engagement_growth": "Engagement Growth",
    "dashboard.reach_trends": "Reach trends over the last 7 days",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.ai_performance": "AI Performance",
    "dashboard.enhanced_edit": "ENHANCED EDIT",
    "dashboard.authentic_look": "AUTHENTIC LOOK",
    "dashboard.connected_to": "Connected to @{user}",
    "dashboard.connect_ig_msg": "Connect your Instagram account in Settings to start posting.",
    "dashboard.authenticity_msg": "Post via InstaAgent to see AI-driven authenticity metrics.",
    "dashboard.eng_short": "Eng.",
    "dashboard.returns": "returns",
    "dashboard.live": "Live",
    "dashboard.inactive": "Inactive",
    "dashboard.connected": "Connected",
    "dashboard.not_linked": "No Instagram linked",
    "create.title": "Create New Post",
    "create.photo_label": "Product Photo",
    "create.photo_desc": "Upload a high-quality photo of your product",
    "create.product_name": "Product Name",
    "create.price": "Selling Price (₹)",
    "create.generate_btn": "Generate AI Caption",
    "create.advanced_options": "Advanced Post Options",
    "create.schedule_label": "Schedule for later",
    "create.post_now": "Post immediately",
    "create.date": "Post Date",
    "create.time": "Post Time",
    "create.publish_btn": "Publish to Instagram",
    "create.success_msg": "Success! Your post is ready.",
    "create.failed_msg": "Failed to create post. Please try again.",
    "settings.title": "Settings",
    "settings.subtitle": "Manage your profile and integrations",
    "settings.guide_title": "🚀 Quick Setup Guide",
    "settings.guide_steps": "{val}/3 steps complete — finish setup in 2 mins",
    "settings.step1_title": "Connect Instagram",
    "settings.step1_desc": "Lets InstaAgent post on your behalf",
    "settings.step2_title": "Link WhatsApp Number",
    "settings.step2_desc": "Enter your WhatsApp number below",
    "settings.step3_title": "Set Auto-Post Time",
    "settings.step3_desc": "Choose when your posts go live",
    "settings.how_it_works": "💡 How it works: Connect Instagram → WhatsApp a photo → AI auto-posts for you!",
    "settings.profile_info": "👤 Profile Information",
    "settings.full_name": "Full Name",
    "settings.phone": "Phone",
    "settings.city": "City",
    "settings.post_time": "Auto-Post Time (IST)",
    "settings.post_time_desc": "Scheduled posts are automatically published at this time",
    "settings.lang_title": "🌐 App Language",
    "settings.lang_desc": "All UI labels will translate immediately when you save.",
    "settings.select_lang": "Select Language",
    "settings.ig_integration": "Instagram Integration",
    "settings.ig_connected": "Connected",
    "settings.ig_disconnect": "Disconnect",
    "settings.ig_desc": "Connect IG Business to enable auto-posting & AI captions.",
    "settings.ig_connect_btn": "Connect Instagram",
    "settings.wa_bot": "WhatsApp Bot",
    "settings.wa_desc": "Send photos on WhatsApp → Post to Instagram",
    "settings.wa_linked": "Linked",
    "settings.wa_not_linked": "Not linked",
    "settings.wa_number": "Your WhatsApp Number",
    "settings.wa_number_desc": "Enter your number used to send photos",
    "settings.wa_how_to": "📱 How to use: Save +91 888 222 5555 → Send photo → Review & Post! 🚀",
    "posts.title": "My Posts",
    "posts.subtitle": "Click any post to see full details, captions & hashtags",
    "posts.no_posts": "No posts yet",
    "posts.create_first": "Create your first post to see it here!",
    "posts.original": "Original",
    "posts.post_photo": "Post Photo",
    "posts.ai_caption_label": "📝 AI Caption (Claude SEO Optimized)",
    "posts.hashtag_label": "# Hashtags",
    "posts.hashtag_copy_hint": "💡 Click any hashtag to copy it",
    "posts.created_at": "📅 Created",
    "posts.scheduled_at": "⏰ Scheduled",
    "posts.posted_at": "✅ Posted",
    "posts.view_on_ig": "View on Instagram",
    "posts.read_more": "click to read more",
    "posts.delete_confirm": "Delete this post permanently?",
    "posts.delete_btn": "🗑 Delete",
    "posts.deleting": "Deleting...",
    "posts.publish_success": "✅ Posted!",
    "posts.publish_failed": "❌ Publish failed",
    "billing.title": "Billing & Subscriptions",
    "billing.subtitle": "Manage your plan and usage limits",
    "billing.current_plan": "Current Plan",
    "billing.status": "Status",
    "billing.usage_limit": "{used} / {limit} posts used this month",
    "billing.cancel_btn": "Cancel Plan",
    "billing.monthly_usage": "Monthly Usage",
    "billing.active": "Already Active",
    "billing.downgrade": "Downgrade to Free",
    "billing.upgrade_to": "Upgrade to {name}",
    "billing.footer": "Payments are processed securely via Razorpay. Subscriptions auto-renew monthly. Cancel anytime.",
    "analytics.title": "Analytics",
    "analytics.subtitle": "Real-time performance tracking for your account",
    "analytics.no_data": "No Analytics Yet",
    "analytics.no_data_msg": "Connect your Instagram account and publish your first post to start seeing real engagement data here.",
    "analytics.connect_btn": "Connect Instagram →",
    "analytics.create_btn": "Create First Post →",
    "analytics.followers": "Followers",
    "analytics.avg_likes": "Avg Likes",
    "analytics.engagement": "Engagement",
    "analytics.reach": "Reach",
    "analytics.growth_title": "30-Day Reach Growth",
    "analytics.growth_subtitle": "Performance over the last month",
    "analytics.insights": "Account Insights",
    "analytics.profile_views": "Profile Views",
    "analytics.website_clicks": "Website Clicks",
    "analytics.impressions": "Impressions",
    "analytics.saves": "Saves",
    "analytics.top_posts": "Top Performing Posts",
    "analytics.no_posts": "No posts found for this period",
  },
  hi: {
    dashboard: "डैशबोर्ड", create: "पोस्ट बनाएं", posts: "मेरे पोस्ट",
    analytics: "एनालिटिक्स", billing: "बिलिंग", telegram: "टेलीग्राम बॉट",
    aggregator: "एग्रीगेटर", admin: "एडमिन पैनल", settings: "सेटिंग्स", logout: "साइन आउट",
    menu: "मेनू", monthly_usage: "मासिक उपयोग",
    "aggregator.title": "मार्केट इंटेलिजेंस",
    "aggregator.subtitle": "एग्रीगेटर",
    "aggregator.add_account": "खाता जोड़ें",
    "aggregator.tracked_accounts": "ट्रैक किए गए खाते",
    "aggregator.generate_insights": "AI विश्लेषण प्राप्त करें",
    "aggregator.ai_strategy": "क्लाउड रणनीति",
    "aggregator.post_ideas": "पोस्ट विचार",
    "aggregator.market_trends": "मार्केट ट्रेंड्स",
    "aggregator.feed_title": "प्रतिस्पर्धी फ़ीड",
    "aggregator.type_owned": "स्वयं का",
    "aggregator.type_competitor": "प्रतिस्पर्धी",
    "aggregator.type_owned_full": "स्वयं का खाता",
    "aggregator.type_competitor_full": "प्रतिस्पर्धी खाता",
    "aggregator.account_type": "खाते का प्रकार",
    "aggregator.synced": "सिंक हो गया",
    "aggregator.syncing": "सिंक हो रहा है",
    "aggregator.no_accounts": "अभी तक कोई खाता नहीं जोड़ा गया है।",
    "aggregator.fetching_data": "डेटा प्राप्त कर रहा है...",
    "aggregator.sync_pending_banner": "बैकग्राउंड में सिंक हो रहा है • लगभग 30 सेकंड लगेंगे",
    "aggregator.account_added_msg": "खाता जुड़ गया! जल्द ही डेटा सिंक होगा।",
    "aggregator.insights_generated_msg": "AI विश्लेषण तैयार है!",
    "aggregator.add_modal_title": "इंस्टाग्राम खाता जोड़ें",
    "aggregator.add_modal_desc": "ट्रैक करने के लिए प्रतियोगी या अपने स्वयं के खाते का यूजरनेम दर्ज करें।",
    "aggregator.ig_username": "इंस्टाग्राम यूजरनेम",
    "aggregator.track_btn": "ट्रैकिंग शुरू करें",
    "aggregator.refresh": "रिफ्रेश",
    "aggregator.refresh_triggered": "सिंक शुरू!",
    "aggregator.save_to_my_posts": "मेरे पोस्ट में सहेजें",
    "aggregator.save_success": "लाइब्रेरी में सहेजा गया!",
    "aggregator.feed_tab": "फ़ीड",
    "aggregator.analytics_tab": "एनालिटिक्स",
    "aggregator.accounts_tab": "प्रोफाइल",
    "aggregator.sort_recent": "नवीनतम",
    "aggregator.sort_top": "टॉप रेटेड",
    "aggregator.enable_alerts": "एंगेजमेंट अलर्ट",
    "aggregator.alert_threshold": "अलर्ट यदि ER >",
    "aggregator.alerts_updated_msg": "अलर्ट सेटिंग्स सहेजी गईं!",
    "aggregator.avg_weekly_posts": "औसत साप्ताहिक पोस्ट",
    "aggregator.competitor_avg": "प्रतियोगी औसत: {val}",
    "aggregator.top_format": "सबसे वायरल फॉर्मेट",
    "aggregator.highest_er": "उच्चतम एंगेजमेंट",
    "aggregator.network_er": "आपका औसत ER",
    "aggregator.owned_account": "प्राथमिक खाता",
    "aggregator.posting_frequency": "पोस्टिंग फ्रीक्वेंसी",
    "aggregator.trending_hashtags": "ट्रेंडिंग हैशटैग",
    "aggregator.engagement_by_format": "फॉर्मेट द्वारा एंगेजमेंट",
    "aggregator.competitor_comparison": "प्रतियोगी बेंचमार्क",
    "aggregator.account": "खाता",
    "aggregator.followers": "फ़ॉलोअर्स",
    "aggregator.avg_er": "औसत ER",
    "aggregator.weekly_posts": "पोस्ट/सप्ताह",
    "aggregator.you": "आप",
    "aggregator.owned": "स्वयं का",
    "aggregator.content_sentiment": "कंटेंट वाइब",
    "aggregator.top_format_ai": "विजेता फॉर्मेट",
    "aggregator.weak_spots": "कमजोर कड़ियाँ",
    "aggregator.ai_footer": "प्रति खाता नवीनतम 30 पोस्ट से प्राप्त अंतर्दृष्टि।",
    "aggregator.confirm_delete": "इस खाते को ट्रैक करना बंद करें?",
    "aggregator.remove_account": "खाता हटाएँ",
    "admin_aggregator": "ट्रैक किए गए प्रोफाइल",
    "common.cancel": "रद्द करें",
    "common.save": "बदलाव सहेजें",
    "common.upload": "फ़ोटो डालें",
    "common.generate": "बनाएं",
    "common.post_now": "अभी पोस्ट करें",
    "common.schedule": "समय तय करें",
    "common.processing": "काम चल रहा है...",
    "common.ready": "तैयार है",
    "common.posted": "पोस्ट हो गया",
    "common.failed": "फ़ेल हो गया",
    "common.scheduled": "शेड्यूल किया गया",
    "common.no_posts": "कोई पोस्ट नहीं मिला",
    "common.first_photo": "अपनी पहली फ़ोटो डालें",
    "common.error": "कुछ गलत हो गया",
    "common.success": "काम सफल रहा",
    "billing.plan": "आपका प्लान",
    "billing.upgrade": "अभी अपग्रेड करें",
    "settings.language": "भाषा",
    "settings.profile": "प्रोफ़ाइल सेटिंग",
    "settings.instagram": "इंस्टाग्राम कनेक्शन",
    "dashboard.greeting_morning": "शुभ प्रभात",
    "dashboard.greeting_afternoon": "नमस्कार",
    "dashboard.greeting_evening": "शुभ संध्या",
    "dashboard.analytics_overview": "एनालिटिक्स ओवरव्यू",
    "dashboard.monthly_posts": "मासिक पोस्ट",
    "dashboard.reach": "रीच",
    "dashboard.engagement": "एंगेजमेंट",
    "dashboard.account_status": "खाते की स्थिति",
    "dashboard.engagement_growth": "एंगेजमेंट ग्रोथ",
    "dashboard.reach_trends": "पिछले 7 दिनों का रीच ट्रेंड",
    "dashboard.recent_activity": "हाल की गतिविधि",
    "dashboard.ai_performance": "AI परफॉर्मेंस",
    "dashboard.enhanced_edit": "बेहतरीन एडिट",
    "dashboard.authentic_look": "असली लुक",
    "dashboard.connected_to": "@{user} से जुड़ा हुआ है",
    "dashboard.connect_ig_msg": "पोस्ट शुरू करने के लिए सेटिंग्स में अपना इंस्टाग्राम अकाउंट जोड़ें।",
    "dashboard.authenticity_msg": "AI-संचालित ऑथेंटिसिटी मेट्रिक्स देखने के लिए InstaAgent के ज़रिए पोस्ट करें।",
    "dashboard.eng_short": "एंगेजमेंट",
    "dashboard.returns": "रिटर्न",
    "dashboard.live": "लाइव",
    "dashboard.inactive": "इनएक्टिव",
    "dashboard.connected": "जुड़ा हुआ है",
    "dashboard.not_linked": "इंस्टाग्राम लिंक नहीं है",
    "create.title": "नया पोस्ट बनाएं",
    "create.photo_label": "प्रोडक्ट फोटो",
    "create.photo_desc": "अपने प्रोडक्ट की एक अच्छी फोटो अपलोड करें",
    "create.product_name": "प्रोडक्ट का नाम",
    "create.price": "बेचने की कीमत (₹)",
    "create.generate_btn": "AI कैप्शन बनाएं",
    "create.advanced_options": "अडवांस पोस्ट विकल्प",
    "create.schedule_label": "बाद के लिए समय तय करें",
    "create.post_now": "अभी पोस्ट करें",
    "create.date": "पोस्ट की तारीख",
    "create.time": "पोस्ट का समय",
    "create.publish_btn": "इंस्टाग्राम पर डालें",
    "create.success_msg": "सफल! आपकी पोस्ट तैयार है।",
    "create.failed_msg": "पोस्ट बनाने में विफल। कृपया फिर से कोशिश करें।",
    "settings.title": "सेटिंग्स",
    "settings.subtitle": "अपनी प्रोफ़ाइल और इंटीग्रेशन मैनेज करें",
    "settings.guide_title": "🚀 क्विक सेटअप गाइड",
    "settings.guide_steps": "{val}/3 चरण पूरे — 2 मिनट में सेटअप खत्म करें",
    "settings.step1_title": "इंस्टाग्राम कनेक्ट करें",
    "settings.step1_desc": "InstaAgent को आपकी ओर से पोस्ट करने दें",
    "settings.step2_title": "व्हाट्सएप नंबर लिंक करें",
    "settings.step2_desc": "अपना व्हाट्सएप नंबर नीचे दर्ज करें",
    "settings.step3_title": "ऑटो-पोस्ट समय सेट करें",
    "settings.step3_desc": "चुनें कि आपकी पोस्ट कब लाइव होंगी",
    "settings.how_it_works": "💡 यह कैसे काम करता है: इंस्टाग्राम कनेक्ट करें → फोटो व्हाट्सएप करें → AI आपके लिए ऑटो-पोस्ट करेगा!",
    "settings.profile_info": "👤 प्रोफ़ाइल जानकारी",
    "settings.full_name": "पूरा नाम",
    "settings.phone": "फ़ोन",
    "settings.city": "शहर",
    "settings.post_time": "ऑटो-पोस्ट समय (IST)",
    "settings.post_time_desc": "निर्धारित पोस्ट इस समय अपने आप प्रकाशित हो जाती हैं",
    "settings.lang_title": "🌐 ऐप की भाषा",
    "settings.lang_desc": "आपके द्वारा सेव करने पर सभी UI लेबल तुरंत ट्रांसलेट हो जाएंगे।",
    "settings.select_lang": "भाषा चुनें",
    "settings.ig_integration": "इंस्टाग्राम इंटीग्रेशन",
    "settings.ig_connected": "जुड़ा हुआ है",
    "settings.ig_disconnect": "डिस्कनेक्ट करें",
    "settings.ig_desc": "ऑटो-पोस्टिंग और AI कैप्शन सक्षम करने के लिए IG बिजनेस कनेक्ट करें।",
    "settings.ig_connect_btn": "इंस्टाग्राम कनेक्ट करें",
    "settings.wa_bot": "व्हाट्सएप बॉट",
    "settings.wa_desc": "व्हाट्सएप पर फोटो भेजें → इंस्टाग्राम पर पोस्ट करें",
    "settings.wa_linked": "लिंक किया गया",
    "settings.wa_not_linked": "लिंक नहीं है",
    "settings.wa_number": "आपका व्हाट्सएप नंबर",
    "settings.wa_number_desc": "फोटो भेजने के लिए इस्तेमाल किया जाने वाला अपना नंबर दर्ज करें",
    "settings.wa_how_to": "📱 कैसे इस्तेमाल करें: +91 888 222 5555 सेव करें → फोटो भेजें → रिव्यू और पोस्ट! 🚀",
    "posts.title": "मेरे पोस्ट",
    "posts.subtitle": "पूरा विवरण, कैप्शन और हैशटैग देखने के लिए किसी भी पोस्ट पर क्लिक करें",
    "posts.no_posts": "अभी तक कोई पोस्ट नहीं",
    "posts.create_first": "इसे यहाँ देखने के लिए अपना पहला पोस्ट बनाएँ!",
    "posts.original": "ओरिजिनल",
    "posts.post_photo": "पोस्ट फोटो",
    "posts.ai_caption_label": "📝 AI कैप्शन (क्लाउड SEO अनुकूलित)",
    "posts.hashtag_label": "# हैशटैग",
    "posts.hashtag_copy_hint": "💡 कॉपी करने के लिए किसी भी हैशटैग पर क्लिक करें",
    "posts.created_at": "📅 बनाया गया",
    "posts.scheduled_at": "⏰ निर्धारित",
    "posts.posted_at": "✅ पोस्ट किया गया",
    "posts.view_on_ig": "इंस्टाग्राम पर देखें",
    "posts.read_more": "और पढ़ने के लिए क्लिक करें",
    "posts.delete_confirm": "इस पोस्ट को हमेशा के लिए हटा दें?",
    "posts.delete_btn": "🗑 हटाएँ",
    "posts.deleting": "हटाया जा रहा है...",
    "posts.publish_success": "✅ पोस्ट हो गया!",
    "posts.publish_failed": "❌ पोस्ट करने में विफल",
    "billing.title": "बिलिंग और सदस्यता",
    "billing.subtitle": "अपनी योजना और उपयोग सीमाएँ प्रबंधित करें",
    "billing.current_plan": "वर्तमान योजना",
    "billing.status": "स्थिति",
    "billing.usage_limit": "इस महीने {used} / {limit} पोस्ट उपयोग किए गए",
    "billing.cancel_btn": "योजना रद्द करें",
    "billing.monthly_usage": "मासिक उपयोग",
    "billing.active": "पहले से सक्रिय",
    "billing.downgrade": "फ्री में डाउनग्रेड करें",
    "billing.upgrade_to": "{name} में अपग्रेड करें",
    "billing.footer": "Razorpay के माध्यम से सुरक्षित भुगतान। सदस्यता हर महीने अपने आप रिन्यू होती है। कभी भी रद्द करें।",
    "analytics.title": "एनालिटिक्स",
    "analytics.subtitle": "आपके खाते के लिए रियल-टाइम प्रदर्शन ट्रैकिंग",
    "analytics.no_data": "अभी तक कोई विश्लेषण नहीं",
    "analytics.no_data_msg": "अपना इंस्टाग्राम अकाउंट कनेक्ट करें और वास्तविक जुड़ाव डेटा देखना शुरू करने के लिए अपना पहला पोस्ट प्रकाशित करें।",
    "analytics.connect_btn": "इंस्टाग्राम कनेक्ट करें →",
    "analytics.create_btn": "पहला पोस्ट बनाएं →",
    "analytics.followers": "फ़ॉलोअर्स",
    "analytics.avg_likes": "औसत लाइक्स",
    "analytics.engagement": "जुड़ाव (Engagement)",
    "analytics.reach": "पहुँच (Reach)",
    "analytics.growth_title": "30-दिन की पहुँच वृद्धि (Growth)",
    "analytics.growth_subtitle": "पिछले महीने का प्रदर्शन",
    "analytics.insights": "खाता अंतर्दृष्टि",
    "analytics.profile_views": "प्रोफ़ाइल दृश्य",
    "analytics.website_clicks": "वेबसाइट क्लिक",
    "analytics.impressions": "इंप्रेशन",
    "analytics.saves": "सेव",
    "analytics.top_posts": "शीर्ष प्रदर्शन करने वाले पोस्ट",
    "analytics.no_posts": "इस अवधि के लिए कोई पोस्ट नहीं मिला",
  },
  te: {
    dashboard: "డ్యాష్‌బోర్డ్", create: "పోస్ట్ సృష్టించండి", posts: "నా పోస్ట్‌లు",
    analytics: "అనలిటిక్స్", billing: "బిల్లింగ్", telegram: "టెలిగ్రామ్ బాట్",
    aggregator: "అగ్రిగేటర్", admin: "అడ్మిన్ ప్యానెల్", settings: "సెట్టింగ్‌లు", logout: "లాగ్ అవుట్",
    menu: "మెనూ", monthly_usage: "నెలవారీ వినియోగం",
    "aggregator.title": "మార్కెట్ ఇంటెలిజెన్స్",
    "aggregator.subtitle": "అగ్రిగేటర్",
    "aggregator.add_account": "ఖాతాను జోడించండి",
    "aggregator.tracked_accounts": "ట్రాక్ చేయబడిన ఖాతాలు",
    "aggregator.generate_insights": "AI అంతర్దృష్టులు",
    "aggregator.ai_strategy": "క్లాడ్ వ్యూహం",
    "aggregator.post_ideas": "పోస్ట్ ఐడియాస్",
    "aggregator.market_trends": "మార్కెట్ ట్రెండ్స్",
    "aggregator.feed_title": "పోటీ ఫీడ్",
    "aggregator.type_owned": "సొంత",
    "aggregator.type_competitor": "పోటీదారు",
    "aggregator.type_owned_full": "సొంత ఖాతా",
    "aggregator.type_competitor_full": "పోటీదారు ఖాతా",
    "aggregator.account_type": "ఖాతా రకం",
    "aggregator.synced": "సింక్ అయింది",
    "aggregator.syncing": "సింక్ అవుతోంది",
    "aggregator.no_accounts": "ఇంకా ఖాతాలు లేవు.",
    "aggregator.fetching_data": "డేటా సేకరిస్తోంది...",
    "aggregator.sync_pending_banner": "బ్యాక్‌గ్రౌండ్‌లో సింక్ అవుతోంది • ~30 సెకన్లు పడుతుంది",
    "aggregator.account_added_msg": "ఖాతా జోడించబడింది!",
    "aggregator.insights_generated_msg": "AI అంతర్దృష్టులు సిద్ధం!",
    "aggregator.add_modal_title": "ఇన్‌స్టాగ్రామ్ ఖాతాను జోడించు",
    "aggregator.add_modal_desc": "ట్రాక్ చేయడానికి పోటీదారు లేదా మీ ఖాతా పేరును నమోదు చేయండి.",
    "aggregator.ig_username": "యూజర్ నేమ్",
    "aggregator.track_btn": "ట్రాకింగ్ ప్రారంభించండి",
    "aggregator.refresh": "రిఫ్రెష్",
    "aggregator.refresh_triggered": "సింక్ ప్రారంభం!",
    "aggregator.save_to_my_posts": "నా పోస్ట్‌లలో సేవ్ చేయి",
    "aggregator.save_success": "లైబ్రరీలో సేవ్ చేయబడింది!",
    "aggregator.feed_tab": "ఫీడ్",
    "aggregator.analytics_tab": "అనలిటిక్స్",
    "aggregator.accounts_tab": "ప్రొఫైల్స్",
    "aggregator.sort_recent": "ఇటీవలి",
    "aggregator.sort_top": "టాప్ రేటెడ్",
    "aggregator.enable_alerts": "ఎంగేజ్మెంట్ అలర్ట్స్",
    "aggregator.alert_threshold": "అలర్ట్ ER > ఉంటే",
    "aggregator.alerts_updated_msg": "అలర్ట్ సెట్టింగ్‌లు సేవ్ చేయబడ్డాయి!",
    "aggregator.avg_weekly_posts": "సగటు వారపు పోస్ట్‌లు",
    "aggregator.competitor_avg": "పోటీదారు సగటు: {val}",
    "aggregator.top_format": "వైరల్ ఫార్మాట్",
    "aggregator.highest_er": "అత్యధిక ఎంగేజ్మెంట్",
    "aggregator.network_er": "మీ సగటు ER",
    "aggregator.owned_account": "ప్రధాన ఖాతా",
    "aggregator.posting_frequency": "పోస్టింగ్ ఫ్రీక్వెన్సీ",
    "aggregator.trending_hashtags": "ట్రెండింగ్ హ్యాష్‌ట్యాగ్‌లు",
    "aggregator.engagement_by_format": "ఫార్మాట్ వారీగా ఎంగేజ్మెంట్",
    "aggregator.competitor_comparison": "పోటీదారుల బెంచ్‌మార్క్",
    "aggregator.account": "ఖాతా",
    "aggregator.followers": "ఫాలోవర్స్",
    "aggregator.avg_er": "సగటు ER",
    "aggregator.weekly_posts": "పోస్ట్‌లు/వారం",
    "aggregator.you": "మీరు",
    "aggregator.owned": "సొంత",
    "aggregator.content_sentiment": "కంటెంట్ వైబ్",
    "aggregator.top_format_ai": "విజేత ఫార్మాట్",
    "aggregator.weak_spots": "బలహీనతలు",
    "aggregator.ai_footer": "ప్రతి ఖాతాకు తాజా 30 పోస్ట్‌ల నుండి సేకరించిన విశ్లేషణ.",
    "aggregator.confirm_delete": "ఈ ఖాతాను ట్రాక్ చేయడం ఆపాలా?",
    "aggregator.remove_account": "ఖాతాను తొలగించు",
    "admin_aggregator": "ట్రాక్ చేయబడిన ప్రోఫೈల్స్",
    "common.cancel": "రద్దు",
    "common.save": "మార్పులను సేవ్ చేయి",
    "common.upload": "అప్‌లోడ్ చేయి",
    "common.generate": "సృష్టించు",
    "common.post_now": "ఇప్పుడే పోస్ట్ చేయి",
    "common.schedule": "షెడ్యూల్ చేయి",
    "common.processing": "ప్రోసెస్ అవుతోంది...",
    "common.ready": "సిద్ధంగా ఉంది",
    "common.posted": "పోస్ట్ చేయబడింది",
    "common.failed": "విఫలమైంది",
    "common.scheduled": "షెಡ్యూల్ చేయబడింది",
    "common.no_posts": "పోస్ట్‌లు ఏవీ లేవు",
    "common.first_photo": "మీ మొదటి ఫోటోను అప్‌లోడ్ చేయండి",
    "common.error": "ఏదో తప్పు జరిగింది",
    "common.success": "పని విజయవంతమైంది",
    "billing.plan": "మీ ప్లాన్",
    "billing.upgrade": "ఇప్పుడే అప్‌గ్రేడ్ చేయండి",
    "settings.language": "భాష",
    "settings.profile": "ప్రొఫైల్ సెట్టింగ్‌లు",
    "settings.instagram": "ఇన్‌స్టాగ్రామ్ కనెక్షన్",
    "dashboard.greeting_morning": "శుభోదయం",
    "dashboard.greeting_afternoon": "మధ్యాహ్న వందనం",
    "dashboard.greeting_evening": "శుభ సాయంత్రం",
    "dashboard.analytics_overview": "ఎనలిటిక్స్ ఓవర్‌వ్యూ",
    "dashboard.monthly_posts": "నెలవారీ పోస్ట్‌లు",
    "dashboard.reach": "రీచ్",
    "dashboard.engagement": "ఎంగేజ్‌మెంట్",
    "dashboard.account_status": "ఖాతా స్థితి",
    "dashboard.engagement_growth": "ఎంగేజ్‌మెంట్ గ్రోత్",
    "dashboard.reach_trends": "గత 7 రోజుల రీచ్ ట్రెండ్స్",
    "dashboard.recent_activity": "ఇటీవలి కార్యకలాపాలు",
    "dashboard.ai_performance": "AI పనితీరు",
    "dashboard.enhanced_edit": "మెరుగైన ఎడిట్",
    "dashboard.authentic_look": "అసలైన లుక్",
    "dashboard.connected_to": "@{user} కి కనెక్ట్ చేయబడింది",
    "dashboard.connect_ig_msg": "పోస్ట్ చేయడం ప్రారంభించడానికి సెట్టింగ్స్‌లో మీ ఇన్‌స్టాగ్రామ్ ఖాతాను కనెక్ట్ చేయండి.",
    "dashboard.authenticity_msg": "AI-ఆధారిత ప్రామాణికత కొలమానాలను చూడటానికి InstaAgent ద్వారా పోస్ట్ చేయండి.",
    "dashboard.eng_short": "ఎంగేజ్.",
    "dashboard.returns": "రిటర్న్స్",
    "dashboard.live": "లైవ్",
    "dashboard.inactive": "నిష్క్రియ",
    "dashboard.connected": "కనెక్ట్ చేయబడింది",
    "dashboard.not_linked": "ఇన్‌స్టాగ్రామ్ లింక్ చేయబడలేదు",
    "create.title": "కొత్త పోస్ట్‌ను సృష్టించండి",
    "create.photo_label": "ఉత్పత్తి ఫోటో",
    "create.photo_desc": "మీ ఉత్పత్తి యొక్క అధిక నాణ్యత గల ఫోటోను అప్‌లోడ్ చేయండి",
    "create.product_name": "ఉత్పత్తి పేరు",
    "create.price": "అమ్మకపు ధర (₹)",
    "create.generate_btn": "AI శీర్షికను సృష్టించండి",
    "create.advanced_options": "అధునాతన పోస్ట్ ఎంపికలు",
    "create.schedule_label": "తర్వాత కోసం షెడ్యూల్ చేయండి",
    "create.post_now": "ఇప్పుడే పోస్ట్ చేయండి",
    "create.date": "పోస్ట్ తేదీ",
    "create.time": "పోస్ట్ సమయం",
    "create.publish_btn": "ఇన్‌స్టాగ్రామ్‌లో ప్రచురించండి",
    "create.success_msg": "విజయం! మీ పోస్ట్ సిద్ధంగా ఉంది.",
    "create.failed_msg": "పోస్ట్‌ను సృష్టించడం విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
  },
  ta: {
    dashboard: "டாஷ்போர்டு", create: "பதிவை உருவாக்கு", posts: "எனது பதிவுகள்",
    analytics: "பகுப்பாய்வு", billing: "பில்லிங்", telegram: "டெலிகிராம் பாட்",
    aggregator: "அக்ரிகேட்டர்", admin: "நிர்வாக குழு", settings: "அமைப்புகள்", logout: "வெளியேறு",
    menu: "மெனு", monthly_usage: "மாதாந்திர பயன்பாடு",
    "aggregator.title": "சந்தை நுண்ணறிவு",
    "aggregator.subtitle": "அக்ரிகேட்டர்",
    "aggregator.add_account": "கணக்கைச் சேர்",
    "aggregator.tracked_accounts": "கண்காணிக்கப்படும் கணக்குகள்",
    "aggregator.generate_insights": "AI நுண்ணறிவு",
    "aggregator.ai_strategy": "கிளாட் உத்தி",
    "aggregator.post_ideas": "பதிவு யோசனைகள்",
    "aggregator.market_trends": "சந்தை போக்குகள்",
    "aggregator.feed_title": "போட்டி ஊட்டம்",
    "aggregator.type_owned": "சொந்தம்",
    "aggregator.type_competitor": "போட்டியாளர்",
    "aggregator.type_owned_full": "சொந்த கணக்கு",
    "aggregator.type_competitor_full": "போட்டியாளர் கணக்கு",
    "aggregator.account_type": "கணக்கு வகை",
    "aggregator.synced": "ஒத்திசைக்கப்பட்டது",
    "aggregator.syncing": "ஒத்திசைக்கப்படுகிறது",
    "aggregator.no_accounts": "இன்னும் கணக்குகள் சேர்க்கப்படவில்லை.",
    "aggregator.fetching_data": "தரவு சேகரிக்கப்படுகிறது...",
    "aggregator.sync_pending_banner": "பின்னணியில் ஒத்திசைக்கப்படுகிறது • ~30 வினாடிகள் ஆகும்",
    "aggregator.account_added_msg": "கணக்கு சேர்க்கப்பட்டது!",
    "aggregator.insights_generated_msg": "AI நுண்ணறிவு தயார்!",
    "aggregator.add_modal_title": "இன்ஸ்டாகிராம் கணக்கைச் சேர்",
    "aggregator.add_modal_desc": "கண்காணிக்க போட்டியாளர் அல்லது உங்கள் கணக்கின் பெயரை உள்ளிடவும்.",
    "aggregator.ig_username": "பயனர் பெயர்",
    "aggregator.track_btn": "கண்காணிப்பைத் தொடங்கு",
    "aggregator.refresh": "புதுப்பி",
    "aggregator.refresh_triggered": "ஒத்திசைவு தொடங்கியது!",
    "aggregator.save_to_my_posts": "எனது பதிவுகளில் சேமி",
    "aggregator.save_success": "சேமிக்கப்பட்டது!",
    "aggregator.feed_tab": "ஊட்டம்",
    "aggregator.analytics_tab": "பகுப்பாய்வு",
    "aggregator.accounts_tab": "சுயவிவரங்கள்",
    "aggregator.sort_recent": "அண்மை",
    "aggregator.sort_top": "சிறந்தவை",
    "aggregator.enable_alerts": "ஈடுபாடு விழிப்பூட்டல்கள்",
    "aggregator.alert_threshold": "ER > ஆக இருந்தால் விழிப்பூட்டு",
    "aggregator.alerts_updated_msg": "அமைப்புகள் சேமிக்கப்பட்டன!",
    "aggregator.avg_weekly_posts": "சராசரி வாராந்திர பதிவுகள்",
    "aggregator.competitor_avg": "போட்டியாளர் சராசரி: {val}",
    "aggregator.top_format": "மிகவும் வைரலான வடிவம்",
    "aggregator.highest_er": "அதிகபட்ச ஈடுபாடு",
    "aggregator.network_er": "உங்கள் சராசரி ER",
    "aggregator.owned_account": "முதன்மை கணக்கு",
    "aggregator.posting_frequency": "பதிவு செய்யும் அதிர்வெண்",
    "aggregator.trending_hashtags": "பிரபலமான ஹேஷ்டேக்குகள்",
    "aggregator.engagement_by_format": "வடிவ வாரியாக ஈடுபாடு",
    "aggregator.competitor_comparison": "போட்டியாளர் ஒப்பீடு",
    "aggregator.account": "கணக்கு",
    "aggregator.followers": "பின்தொடர்பவர்கள்",
    "aggregator.avg_er": "சராசரி ER",
    "aggregator.weekly_posts": "பதிவுகள்/வாரம்",
    "aggregator.you": "நீங்கள்",
    "aggregator.owned": "சொந்தம்",
    "aggregator.content_sentiment": "உள்ளடக்க உணர்வு",
    "aggregator.top_format_ai": "வெற்றி வடிவம்",
    "aggregator.weak_spots": "பலவீனமான இடங்கள்",
    "aggregator.ai_footer": "ஒவ்வொரு கணக்கிலும் சமீபத்திய 30 பதிவுகளிலிருந்து நுண்ணறிவு.",
    "aggregator.confirm_delete": "இந்தக் கணக்கைக் கண்காணிப்பதை நிறுத்தவா?",
    "aggregator.remove_account": "கணக்கை நீக்கு",
    "admin_aggregator": "கண்காணிக்கப்படும் சுயவிவரங்கள்",
    "common.cancel": "ரத்து",
    "common.save": "மாற்றங்களைச் சேமி",
    "common.upload": "பதிவேற்று",
    "common.generate": "உருவாக்கு",
    "common.post_now": "இப்போதே பதிவிடு",
    "common.schedule": "நேரத்தை ஒதுக்கு",
    "common.processing": "செயலாக்கப்படுகிறது...",
    "common.ready": "தயார்",
    "common.posted": "பதிவிடப்பட்டது",
    "common.failed": "தோல்வி",
    "common.scheduled": "திட்டமிடப்பட்டது",
    "common.no_posts": "பதிவுகள் எதுவும் இல்லை",
    "common.first_photo": "உங்கள் முதல் புகைப்படத்தைப் பதிவேற்றவும்",
    "common.error": "ஏதோ தவறு நடந்துவிட்டது",
    "common.success": "வெற்றிகரமாக முடிந்தது",
    "billing.plan": "உங்கள் திட்டம்",
    "billing.upgrade": "இப்போதே மேம்படுத்தவும்",
    "settings.language": "மொழி",
    "settings.profile": "சுயவிவர அமைப்புகள்",
    "settings.instagram": "இன்ஸ்டாகிராம் இணைப்பு",
    "dashboard.greeting_morning": "காலை வணக்கம்",
    "dashboard.greeting_afternoon": "மதிய வணக்கம்",
    "dashboard.greeting_evening": "மாலை வணக்கம்",
    "dashboard.analytics_overview": "அனலிட்டிக்ஸ் கண்ணோட்டம்",
    "dashboard.monthly_posts": "மாதாந்திர பதிவுகள்",
    "dashboard.reach": "ரீச்",
    "dashboard.engagement": "ஈடுபாடு",
    "dashboard.account_status": "கணக்கு நிலை",
    "dashboard.engagement_growth": "ஈடுபாடு வளர்ச்சி",
    "dashboard.reach_trends": "கடந்த 7 நாட்களில் ரீச் போக்குகள்",
    "dashboard.recent_activity": "சமீபத்திய செயல்பாடு",
    "dashboard.ai_performance": "AI செயல்திறன்",
    "dashboard.enhanced_edit": "மேம்படுத்தப்பட்ட எடிட்",
    "dashboard.authentic_look": "உண்மையான தோற்றம்",
    "dashboard.connected_to": "@{user} உடன் இணைக்கப்பட்டுள்ளது",
    "dashboard.connect_ig_msg": "பதிவிடுவதைத் தொடங்க அமைப்புகளில் உங்கள் இன்ஸ்டாகிராம் கணக்கை இணைக்கவும்.",
    "dashboard.authenticity_msg": "AI-உந்துதல் நம்பகத்தன்மை அளவீடுகளைக் காண InstaAgent வழியாகப் பதிவிடவும்.",
    "dashboard.eng_short": "ஈடுபாடு",
    "dashboard.returns": "திரும்பியவை",
    "dashboard.live": "நேரலை",
    "dashboard.inactive": "செயலற்றது",
    "dashboard.connected": "இணைக்கப்பட்டுள்ளது",
    "dashboard.not_linked": "இன்ஸ்டாகிராம் இணைக்கப்படவில்லை",
    "create.title": "புதிய பதிவை உருவாக்கு",
    "create.photo_label": "தயாரிப்பு புகைப்படம்",
    "create.photo_desc": "உங்கள் தயாரிப்பின் உயர்தர புகைப்படத்தைப் பதிவேற்றவும்",
    "create.product_name": "தயாரிப்பு பெயர்",
    "create.price": "விற்பனை விலை (₹)",
    "create.generate_btn": "AI தலைப்பை உருவாக்கு",
    "create.advanced_options": "மேம்பட்ட பதிவு விருப்பங்கள்",
    "create.schedule_label": "பின்னர் பதிவிட திட்டமிடுங்கள்",
    "create.post_now": "இப்போதே பதிவிடு",
    "create.date": "பதிவு தேதி",
    "create.time": "பதிவு நேரம்",
    "create.publish_btn": "இன்ஸ்டாகிராமில் பதிவிடு",
    "create.success_msg": "வெற்றி! உங்கள் பதிவு தயாராக உள்ளது.",
    "create.failed_msg": "பதிவை உருவாக்குவதில் தோல்வி. மீண்டும் முயற்சிக்கவும்.",
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", create: "ಪೋಸ್ಟ್ ರಚಿಸಿ", posts: "ನನ್ನ ಪೋಸ್ಟ್‌ಗಳು",
    analytics: "ಅನಾಲಿಟಿಕ್ಸ್", billing: "ಬಿಲ್ಲಿಂಗ್", telegram: "ಟೆಲಿಗ್ರಾಮ್ ಬಾಟ್",
    aggregator: "ಅಗ್ರಿಗ್ಗೇಟರ್", admin: "ಅಡ್ಮಿನ್ ಪ್ಯಾನೆಲ್", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", logout: "ಲಾಗ್ ಔಟ್",
    menu: "ಮೆನು", monthly_usage: "ತಿಂಗಳ ಬಳಕೆ",
    "aggregator.title": "ಮಾರುಕಟ್ಟೆ ಬುದ್ಧಿವಂತಿಕೆ",
    "aggregator.subtitle": "ಅಗ್ರಿಗ್ಗೇಟರ್",
    "aggregator.add_account": "ಖಾತೆಯನ್ನು ಸೇರಿಸಿ",
    "aggregator.tracked_accounts": "ಟ್ರ್ಯಾಕ್ ಮಾಡಲಾದ ಖಾತೆಗಳು",
    "aggregator.generate_insights": "AI ಒಳನೋಟಗಳು",
    "aggregator.ai_strategy": "ಕ್ಲಾಡ್ ತಂತ್ರ",
    "aggregator.post_ideas": "ಪೋಸ್ಟ್ ಐಡಿಯಾಗಳು",
    "aggregator.market_trends": "ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳು",
    "aggregator.feed_title": "ಸ್ಪರ್ಧಾತ್ಮಕ ಫೀಡ್",
    "aggregator.type_owned": "ಸೊಂತ",
    "aggregator.type_competitor": "ಸ್ಪರ್ಧಾತ್ಮಕ",
    "aggregator.type_owned_full": "ಸೊಂತ ಖಾತೆ",
    "aggregator.type_competitor_full": "ಸ್ಪರ್ಧಾತ್ಮಕ ಖಾತೆ",
    "aggregator.account_type": "ಖಾತೆ ವಿಧ",
    "aggregator.synced": "ಸಿಂಕ್ ಆಗಿದೆ",
    "aggregator.syncing": "ಸಿಂಕ್ ಆಗುತ್ತಿದೆ",
    "aggregator.no_accounts": "ಇನ್ನೂ ಖಾತೆಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ.",
    "aggregator.fetching_data": "ಡೇಟಾ ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
    "aggregator.sync_pending_banner": "ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ • ~30 ಸೆಕೆಂಡುಗಳು ತಗಲುತ್ತದೆ",
    "aggregator.account_added_msg": "ಖಾತೆಯನ್ನು ಸೇರಿಸಲಾಗಿದೆ!",
    "aggregator.insights_generated_msg": "AI ಒಳನೋಟಗಳು ಸಿದ್ಧವಾಗಿವೆ!",
    "aggregator.add_modal_title": "ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್ ಖಾತೆಯನ್ನು ಸೇರಿಸಿ",
    "aggregator.add_modal_desc": "ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಸ್ಪರ್ಧಿ ಅಥವಾ ನಿಮ್ಮ ಸ್ವಂತ ಖಾತೆಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.",
    "aggregator.ig_username": "ಬಳಕೆದಾರ ಹೆಸರು",
    "aggregator.track_btn": "ಟ್ರ್ಯಾಕಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
    "aggregator.refresh": "ರಿಫ್ರೆಶ್",
    "aggregator.refresh_triggered": "ಸಿಂಕ್ ಪ್ರಾರಂಭ!",
    "aggregator.save_to_my_posts": "ನನ್ನ ಪೋಸ್ಟ್‌ಗಳಲ್ಲಿ ಉಳಿಸಿ",
    "aggregator.save_success": "ಉಳಿಸಲಾಗಿದೆ!",
    "aggregator.feed_tab": "ಫೀಡ್",
    "aggregator.analytics_tab": "ಅನಾಲಿಟಿಕ್ಸ್",
    "aggregator.accounts_tab": "ಪ್ರೊಫೈಲ್ಗಳು",
    "aggregator.sort_recent": "ಇತ್ತೀಚಿನ",
    "aggregator.sort_top": "ಟಾಪ್ ರೇಟೆಡ್",
    "aggregator.enable_alerts": "ಎಂಗೇಜ್‌ಮೆಂಟ್ ಅಲರ್ಟ್‌ಗಳು",
    "aggregator.alert_threshold": "ER > ಇದ್ದರೆ ಎಚ್ಚರಿಸಿ",
    "aggregator.alerts_updated_msg": "ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ!",
    "aggregator.avg_weekly_posts": "ಸರಾಸರಿ ವಾರ ಪೋಸ್ಟ್‌ಗಳು",
    "aggregator.competitor_avg": "ಸ್ಪರ್ಧಿಯ ಸರಾಸರಿ: {val}",
    "aggregator.top_format": "ವೈರಲ್ ಫಾರ್ಮ್ಯಾಟ್",
    "aggregator.highest_er": "ಗರಿಷ್ಠ ಎಂಗೇಜ್‌ಮೆಂಟ್",
    "aggregator.network_er": "ನಿಮ್ಮ ಸರಾಸರಿ ER",
    "aggregator.owned_account": "ಮುಖ್ಯ ಖಾತೆ",
    "aggregator.posting_frequency": "ಪೋಸ್ಟಿಂಗ್ ಫ್ರೀಕ್ವೆನ್ಸಿ",
    "aggregator.trending_hashtags": "ಟ್ರೆಂಡಿಂಗ್ ಹ್ಯಾಶ್‌ಟ್ಯಾಗ್‌ಗಳು",
    "aggregator.engagement_by_format": "ಫಾರ್ಮ್ಯಾಟ್ ಮೂಲಕ ಎಂಗೇಜ್‌ಮೆಂಟ್",
    "aggregator.competitor_comparison": "ಸ್ಪರ್ಧಿ ಬೆಂಚ್‌ಮಾರ್ಕ್",
    "aggregator.account": "ಖಾತೆ",
    "aggregator.followers": "ಫಾಲೋವರ್ಸ್",
    "aggregator.avg_er": "ಸರಾಸರಿ ER",
    "aggregator.weekly_posts": "ಪೋಸ್ಟ್‌ಗಳು/ವಾರ",
    "aggregator.you": "ನೀವು",
    "aggregator.owned": "ಸೊಂತ",
    "aggregator.content_sentiment": "ಕಂಟೆಂಟ್ ವೈಬ್",
    "aggregator.top_format_ai": "ಗೆಲ್ಲುವ ಫಾರ್ಮ್ಯಾಟ್",
    "aggregator.weak_spots": "ಬಲಹೀನತೆಗಳು",
    "aggregator.ai_footer": "ಪ್ರತಿ ಖಾತೆಗೆ ಇತ್ತೀಚಿನ 30 ಪೋಸ್ಟ್‌ಗಳಿಂದ ಪಡೆದ ಒಳನೋಟ.",
    "aggregator.confirm_delete": "ಈ ಖಾತೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುವುದು ನಿಲ್ಲಿಸಬೇಕೆ?",
    "aggregator.remove_account": "ಖಾತೆಯನ್ನು ತೆಗೆದುಹಾಕಿ",
    "admin_aggregator": "ಟ್ರ್ಯಾಕ್ ಮಾಡಲಾದ ಪ್ರೊಫೈಲ್‌ಗಳು",
    "common.cancel": "ರದ್ದುಮಾಡಿ",
    "common.save": "ಬದಲಾವಣೆ ಉಳಿಸಿ",
    "common.upload": "ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "common.generate": "ರಚಿಸಿ",
    "common.post_now": "ಈಗಲೇ ಪೋಸ್ಟ್ ಮಾಡಿ",
    "common.schedule": "ಸಮಯ ನಿಗದಿಪಡಿಸಿ",
    "common.processing": "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...",
    "common.ready": "ಸಿದ್ಧವಾಗಿದೆ",
    "common.posted": "ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿದೆ",
    "common.failed": "ವಿಫಲವಾಗಿದೆ",
    "common.scheduled": "ನಿಗದಿಪಡಿಸಲಾಗಿದೆ",
    "common.no_posts": "ಯಾವುದೇ ಪೋಸ್ಟ್ ಕಂಡುಬಂದಿಲ್ಲ",
    "common.first_photo": "ನಿಮ್ಮ ಮೊದಲ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "common.error": "ಏನೋ ತಪ್ಪಾಗಿದೆ",
    "common.success": "ಕಾರ್ಯ ಯಶಸ್ವಿಯಾಗಿದೆ",
    "billing.plan": "ನಿಮ್ಮ ಪ್ಲಾನ್",
    "billing.upgrade": "ಈಗಲೇ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ",
    "settings.language": "ಭಾಷೆ",
    "settings.profile": "ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "settings.instagram": "ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್ ಸಂಪರ್ಕ",
    "dashboard.greeting_morning": "ಶುಭೋದಯ",
    "dashboard.greeting_afternoon": "ಶುಭ ಅಪರಾಹ್ನ",
    "dashboard.greeting_evening": "ಶುಭ ಸಾಯಂಕಾಲ",
    "dashboard.analytics_overview": "ಅನಾಲಿಟಿಕ್ಸ್ ಅವಲೋಕನ",
    "dashboard.monthly_posts": "ಮಾಸಿಕ ಪೋಸ್ಟ್‌ಗಳು",
    "dashboard.reach": "ರೀಚ್",
    "dashboard.engagement": "ಎಂಗೇಜ್‌ಮೆಂಟ್",
    "dashboard.account_status": "ಖಾತೆ ಸ್ಥಿತಿ",
    "dashboard.engagement_growth": "ಎಂಗೇಜ್‌ಮೆಂಟ್ ಬೆಳವಣಿಗೆ",
    "dashboard.reach_trends": "ಕಳೆದ 7 ದಿನಗಳ ರೀಚ್ ಟ್ರೆಂಡ್‌ಗಳು",
    "dashboard.recent_activity": "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    "dashboard.ai_performance": "AI ಕಾರ್ಯಕ್ಷಮತೆ",
    "dashboard.enhanced_edit": "ಸುಧಾರಿತ ಎಡಿಟ್",
    "dashboard.authentic_look": "ಅಸಲಿ ಲುಕ್",
    "dashboard.connected_to": "@{user} ಗೆ ಸಂಪರ್ಕಿಸಲಾಗಿದೆ",
    "dashboard.connect_ig_msg": "ಪೋಸ್ಟ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಲು ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ನಿಮ್ಮ ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್ ಖಾತೆಯನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "dashboard.authenticity_msg": "AI-ಚಾಲಿತ ಅಥೆಂಟಿಸಿಟಿ ಮೆಟ್ರಿಕ್‌ಗಳನ್ನು ನೋಡಲು InstaAgent ಮೂಲಕ ಪೋಸ್ಟ್ ಮಾಡಿ.",
    "dashboard.eng_short": "ಎಂಗೇಜ್.",
    "dashboard.returns": "ರಿಟರ್ನ್ಸ್",
    "dashboard.live": "ಲೈವ್",
    "dashboard.inactive": "ನಿಷ್ಕ್ರಿಯ",
    "dashboard.connected": "ಸಂಪರ್ಕಿಸಲಾಗಿದೆ",
    "dashboard.not_linked": "ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್ ಲಿಂಕ್ ಮಾಡಿಲ್ಲ",
    "create.title": "ಹೊಸ ಪೋಸ್ಟ್ ರಚಿಸಿ",
    "create.photo_label": "ಉತ್ಪನ್ನದ ಫೋಟೋ",
    "create.photo_desc": "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "create.product_name": "ಉತ್ಪನ್ನ ಹೆಸರು",
    "create.price": "ಮಾರಾಟದ ಬೆಲೆ (₹)",
    "create.generate_btn": "AI ಶೀರ್ಷಿಕೆ ರಚಿಸಿ",
    "create.advanced_options": "ಸುಧಾರಿತ ಪೋಸ್ಟ್ ಆಯ್ಕೆಗಳು",
    "create.schedule_label": "ನಂತರಕ್ಕಾಗಿ ವೇಳಾಪಟ್ಟಿ ಮಾಡಿ",
    "create.post_now": "ಈಗಲೇ ಪೋಸ್ಟ್ ಮಾಡಿ",
    "create.date": "ಪೋಸ್ಟ್ ದಿನಾಂಕ",
    "create.time": "ಪೋಸ್ಟ್ ಸಮಯ",
    "create.publish_btn": "ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್‌ಗೆ ಪೋಸ್ಟ್ ಮಾಡಿ",
    "create.success_msg": "ಯಶಸ್ಸು! ನಿಮ್ಮ ಪೋಸ್ಟ್ ಸಿದ್ಧವಾಗಿದೆ.",
    "create.failed_msg": "ಪೋಸ್ಟ್ ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  },
  mr: {
    dashboard: "डॅशबोर्ड", create: "पोस्ट तयार करा", posts: "माझ्या पोस्ट",
    analytics: "अ‍ॅनालिटिक्स", billing: "बिलिंग", telegram: "टेलीग्राम बॉट",
    aggregator: "अ‍ॅग्रिगेटर", admin: "‍अ‍ॅडमिन पॅनेल", settings: "सेटिंग्ज", logout: "साइन आउट",
    menu: "मेनू", monthly_usage: "मासिक वापर",
    "aggregator.title": "मार्केट इंटेलिजेंस",
    "aggregator.subtitle": "अ‍ॅग्रिगेटर",
    "aggregator.add_account": "खाते जोडा",
    "aggregator.tracked_accounts": "ट्रॅक केलेले खाते",
    "aggregator.generate_insights": "AI विश्लेषण",
    "aggregator.ai_strategy": "क्लाउड रणनीती",
    "aggregator.post_ideas": "पोस्ट कल्पना",
    "aggregator.market_trends": "मार्केट ट्रेंड्स",
    "aggregator.feed_title": "प्रतिस्पर्धी फीड",
    "aggregator.type_owned": "स्वतःचे",
    "aggregator.type_competitor": "प्रतिस्पर्धी",
    "aggregator.type_owned_full": "स्वतःचे खाते",
    "aggregator.type_competitor_full": "प्रतिस्पर्धी खाते",
    "aggregator.account_type": "खात्याचा प्रकार",
    "aggregator.synced": "सिंक झाले",
    "aggregator.syncing": "सिंक होत आहे",
    "aggregator.no_accounts": "अद्याप कोणतेही खाते जोडलेले नाही.",
    "aggregator.fetching_data": "डेटा मिळवत आहे...",
    "aggregator.sync_pending_banner": "बॅकग्राउंडमध्ये सिंक होत आहे • सुमारे 30 सेकंद लागतील",
    "aggregator.account_added_msg": "खाते जोडले गेले!",
    "aggregator.insights_generated_msg": "AI विश्लेषण तयार आहे!",
    "aggregator.add_modal_title": "इंस्टाग्राम खाते जोडा",
    "aggregator.add_modal_desc": "ट्रॅक करण्यासाठी स्पर्धक किंवा स्वतःच्या खात्याचे नाव टाका.",
    "aggregator.ig_username": "यूजरनेम",
    "aggregator.track_btn": "ट्रॅकिंग सुरू करा",
    "aggregator.refresh": "रिफ्रेश",
    "aggregator.refresh_triggered": "सिंक सुरू!",
    "aggregator.save_to_my_posts": "माझ्या पोस्टमध्ये जतन करा",
    "aggregator.save_success": "जतन केले गेले!",
    "aggregator.feed_tab": "फीड",
    "aggregator.analytics_tab": "अ‍ॅनालिटिक्स",
    "aggregator.accounts_tab": "प्रोफाइल्स",
    "aggregator.sort_recent": "नुकतेच",
    "aggregator.sort_top": "टॉप रेटेड",
    "aggregator.enable_alerts": "एंगेजमेंट अलर्ट",
    "aggregator.alert_threshold": "ER > असल्यास अलर्ट द्या",
    "aggregator.alerts_updated_msg": "सेटिंग्ज जतन केल्या!",
    "aggregator.avg_weekly_posts": "सरासरी साप्ताहिक पोस्ट",
    "aggregator.competitor_avg": "स्पर्धक सरासरी: {val}",
    "aggregator.top_format": "व्हायरल फॉरमॅट",
    "aggregator.highest_er": "उच्चतम एंगेजमेंट",
    "aggregator.network_er": "तुमचा सरासरी ER",
    "aggregator.owned_account": "मुख्य खाते",
    "aggregator.posting_frequency": "पोस्टिंग फ्रिक्वेन्सी",
    "aggregator.trending_hashtags": "ट्रेंडिंग हॅशटॅग",
    "aggregator.engagement_by_format": "फॉरमॅटनुसार एंगेजमेंट",
    "aggregator.competitor_comparison": "स्पर्धक बेंचमार्क",
    "aggregator.account": "खाते",
    "aggregator.followers": "फॉलोअर्स",
    "aggregator.avg_er": "सरासरी ER",
    "aggregator.weekly_posts": "पोस्ट/आठवडा",
    "aggregator.you": "तुम्ही",
    "aggregator.owned": "स्वतःचे",
    "aggregator.content_sentiment": "कंटेंट वाइब",
    "aggregator.top_format_ai": "विजेता फॉरमॅट",
    "aggregator.weak_spots": "कमकुवत दुवे",
    "aggregator.ai_footer": "प्रत्येक खात्याच्या ताज्या ३० पोस्टवरून मिळालेले विश्लेषण.",
    "aggregator.confirm_delete": "या खात्याचे ट्रॅकिंग थांबवायचे का?",
    "aggregator.remove_account": "खाते काढून टाका",
    "admin_aggregator": "ट्रॅक केलेले प्रोफाइल",
    "common.cancel": "रद्द करा",
    "common.save": "बदल जतन करा",
    "common.upload": "अपलोड करा",
    "common.generate": "तयार करा",
    "common.post_now": "आत्ता पोस्ट करा",
    "common.schedule": "वेळ ठरवा",
    "common.processing": "काम चालू आहे...",
    "common.ready": "तयार आहे",
    "common.posted": "पोस्ट झाले",
    "common.failed": "अयशस्वी",
    "common.scheduled": "शेड्यूल केले",
    "common.no_posts": "कोणतीही पोस्ट सापडली नाही",
    "common.first_photo": "तुमचा पहिला फोटो अपलोड करा",
    "common.error": "काहीतरी चुकीचे घडले",
    "common.success": "काम यशस्वी झाले",
    "billing.plan": "तुमचा प्लॅन",
    "billing.upgrade": "आत्ता अपग्रेड करा",
    "settings.language": "भाषा",
    "settings.profile": "प्रोफाइल सेटिंग्ज",
    "settings.instagram": "इंस्टाग्राम कनेक्शन",
    "dashboard.greeting_morning": "शुभ सकाळ",
    "dashboard.greeting_afternoon": "शुभ दुपार",
    "dashboard.greeting_evening": "शुभ संध्याकाळ",
    "dashboard.analytics_overview": "अ‍ॅनालिटिक्स विहंगावलोकन",
    "dashboard.monthly_posts": "मासिक पोस्ट",
    "dashboard.reach": "रीच",
    "dashboard.engagement": "एंगेजमेंट",
    "dashboard.account_status": "खात्याची स्थिती",
    "dashboard.engagement_growth": "एंगेजमेंट ग्रोथ",
    "dashboard.reach_trends": "गेल्या ७ दिवसांचे रीच ट्रेंड्स",
    "dashboard.recent_activity": "अलीकडील क्रियाकलाप",
    "dashboard.ai_performance": "AI कामगिरी",
    "dashboard.enhanced_edit": "उत्कृष्ट एडिट",
    "dashboard.authentic_look": "अस्सल लुक",
    "dashboard.connected_to": "@{user} शी कनेक्ट केलेले",
    "dashboard.connect_ig_msg": "पोस्ट सुरू करण्यासाठी सेटिंग्जमध्ये आपले इंस्टाग्राम खाते जोडा.",
    "dashboard.authenticity_msg": "AI-चालित ऑथेंटिसिटी मेट्रिक्स पाहण्यासाठी InstaAgent द्वारे पोस्ट करा.",
    "dashboard.eng_short": "एंगेज.",
    "dashboard.returns": "रिटर्न्स",
    "dashboard.live": "लाइव्ह",
    "dashboard.inactive": "निष्क्रिय",
    "dashboard.connected": "कनेक्ट केलेले",
    "dashboard.not_linked": "इंस्टाग्राम लिंक केलेले नाही",
    "create.title": "नवीन पोस्ट तयार करा",
    "create.photo_label": "उत्पादन फोटो",
    "create.photo_desc": "आपल्या उत्पादनाचा उच्च-गुणवत्तेचा फोटो अपलोड करा",
    "create.product_name": "उत्पादनाचे नाव",
    "create.price": "विक्री किंमत (₹)",
    "create.generate_btn": "AI कॅप्शन तयार करा",
    "create.advanced_options": "प्रगत पोस्ट पर्याय",
    "create.schedule_label": "नंतरसाठी वेळ ठरवा",
    "create.post_now": "आता पोस्ट करा",
    "create.date": "पोस्ट तारीख",
    "create.time": "पोस्ट वेळ",
    "create.publish_btn": "इंस्टाग्रामवर प्रकाशित करा",
    "create.success_msg": "यशस्वी! आपली पोस्ट तयार आहे.",
    "create.failed_msg": "पोस्ट तयार करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
  },
};

export function makeLangValue(lang, setLang) {
  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS["en"][key] || key;
  return { lang, t, setLang };
}

// ── FEATURE FLAG CONTEXT ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
export const FeatureCtx = createContext({ features: {}, trialPosts: 5, botUsername: "InstaAgent_bot" });
export const useFeatures = () => useContext(FeatureCtx);
